allowBuilds:
  unrs-resolver: false
minimumReleaseAgeExclude:
  - "@vitest/browser-playwright@5.0.1"
  - "@vitest/browser@5.0.1"
  - "@vitest/mocker@5.0.1"
  - "@vitest/pretty-format@5.0.1"
  - "@vitest/spy@5.0.1"
  - "@vitest/ui@5.0.1"
  - "@vitest/utils@5.0.1"
  - browserslist@4.29.0
  - vitest@5.0.1
