#!/bin/bash

sed -i 's/ def / function /g' "$1"
sed -i 's/^def /function /g' "$1"

sed -r -i 's/'\''/"/g' "$1"

sed -i 's/#/\/\//g' "$1"
sed -i 's/"""$/*\//g' "$1"
sed -i 's/"""/\/*/g' "$1"

sed -i 's/):$/) {/g' "$1"
sed -i 's/:$/) {/g' "$1"

sed -i 's/if /if (/g' "$1"
sed -i 's/else /else (/g' "$1"

sed -i 's/\.append/\.push/g' "$1"

sed -i 's/$/;/g' "$1"
sed -i 's/^;$//g' "$1"
sed -i 's/{;$/{/g' "$1"

sed -r -i 's/_([a-z])/\U\1/g' "$1"


# sed -i 's///g' "$1"

