#!/bin/bash

# Before running, install jslint as described here: https://github.com/reid/node-jslint


jslint --nomen --plusplus --predef requirejs --predef require --predef define --predef mocha --predef describe --predef it --predef window --predef document --predef console --predef alert --predef location --predef setTimeout --predef localStorage --predef indexedDB --predef IDBKeyRange --predef IDBTransaction --predef IDBObjectStore --predef g --predef c --predef bbgm --predef before --predef beforeEach --predef after --predef afterEach --predef Raphael js/core/*.js js/test/*.js js/test/core/*.js js/util/*.js js/*.js js/templates/helpers.js js/lib/IndexedDB-getAll-shim.js js/lib/boxPlot.js js/lib/faces.js js/lib/jquery.dataTables.bbgmSorting.js