// @flow

import { idb } from "../../db";
import type { PickRealized } from "../../../common/types";

/**
 * Save draft order for future picks to the database.
 *
 * @memberOf core.draft
 * @param {Array.<Object>} draftOrder Ordered array of pick objects, as generated by genOrder.
 * @return {Promise}
 */
const setOrder = async (draftOrder: PickRealized[]) => {
    await idb.cache.draftOrder.put({
        rid: 0,
        draftOrder,
    });
};

export default setOrder;
