import type { PlayerBioInfo } from "../../common/types";
import defaultCountries from "../data/defaultCountries";
// import g from "./g";

// The names were generated by tools/names.js, you probably don't want to edit them by hand.
// If the list of countries changes, update the fake age code in getPlayerFakeAge.js!
// This is dynamically resolved with rollup-plugin-alias
import names from "player-names"; // eslint-disable-line
const defaultNames = (names as unknown) as PlayerBioInfo["data"];

const loadNames = (): PlayerBioInfo => {
	/*const gNames = g.get("names");
	if (gNames) {
		// eslint-disable-next-line @typescript-eslint/strict-boolean-expressions
		if (gNames.first) {
			if (Array.isArray(gNames.first)) {
				first = {
					USA: gNames.first,
				};
			} else {
				first = gNames.first;
			}
		}

		// eslint-disable-next-line @typescript-eslint/strict-boolean-expressions
		if (gNames.last) {
			if (Array.isArray(gNames.last)) {
				last = {
					USA: gNames.last,
				};
			} else {
				last = gNames.last;
			}
		}
	}*/

	return {
		countries: defaultCountries,
		data: defaultNames,
	};
};

export default loadNames;
