import type { PlayerBioInfoProcessed } from "../../common/types";
import defaultDefaultColleges from "../data/defaultColleges";
import defaultCountries from "../data/defaultCountries";
import g from "./g";

// The names were generated by tools/names.js, you probably don't want to edit them by hand.
// If the list of countries changes, update the fake age code in getPlayerFakeAge.js!
// This is dynamically resolved with rollup-plugin-alias
import names from "player-names"; // eslint-disable-line
const defaultNames = (names as unknown) as Record<
	string,
	{
		first: Record<string, number>;
		last: Record<string, number>;
	}
>;

const toCumSumArray = (obj: Record<string, number>): [string, number][] => {
	let cumsum = 0;
	return Object.entries(obj).map(([key, value]) => {
		cumsum += value;
		return [key, cumsum];
	});
};

const legacyConvert = (array: [string, number][]) => {
	const obj: Record<string, number> = {};
	let prev = 0;
	for (const row of array) {
		obj[row[0]] = row[1] - prev;
		prev = row[1];
	}
	return obj;
};

const loadNames = (): PlayerBioInfoProcessed => {
	let gPlayerBioInfo = g.get("playerBioInfo");
	const gNames = g.get("names");
	if (!gPlayerBioInfo && gNames) {
		const countryNames = Object.keys(gNames.first);

		const names: Record<
			string,
			{
				first: Record<string, number>;
				last: Record<string, number>;
			}
		> = {};

		if (Array.isArray(gNames.first) && Array.isArray(gNames.last)) {
			// Double legacy!
			names.USA = {
				first: legacyConvert(gNames.first),
				last: legacyConvert(gNames.last),
			};
		} else {
			for (const countryName of countryNames) {
				names[countryName] = {
					first: legacyConvert(gNames.first[countryName]),
					last: legacyConvert(gNames.last[countryName]),
				};
			}
		}

		gPlayerBioInfo = {
			names,
		};
	}

	const names: PlayerBioInfoProcessed["names"] = {};

	for (const [country, info] of Object.entries(defaultNames)) {
		names[country] = {
			first: toCumSumArray(info.first),
			last: toCumSumArray(info.last),
		};

		if (info.colleges) {
			names[country].colleges = toCumSumArray(info.colleges);
		}

		if (info.percentSkipCollege !== undefined) {
			names[country].percentSkipCollege = info.percentSkipCollege;
		}
	}

	return {
		countries: toCumSumArray(defaultCountries),
		defaultColleges: toCumSumArray(defaultDefaultColleges),
		names,
	};
};

export default loadNames;
