import bySport from "../../../common/bySport";
import isSport from "../../../common/isSport";
import type { GameAttributesLeague, Player } from "../../../common/types";
import type { Col } from "../../components/DataTable";

export type ColType =
	| "General"
	| "Position"
	| "Rating"
	| "Stat"
	| "Other"
	| null;

export type LeagueVars = Pick<
	GameAttributesLeague,
	| "userTid"
	| "godMode"
	| "spectator"
	| "phase"
	| "challengeNoRatings"
	| "challengeNoDraftPicks"
	| "challengeNoFreeAgents"
	| "challengeNoTrades"
	| "salaryCapType"
	| "salaryCap"
	| "maxContract"
	| "minContract"
> & {
	season?: string | number;
};

export type TemplateProps = {
	p: Player;
	c: MetaCol;
	vars: LeagueVars;
};

export type MetaCol = Col & {
	cat?: ColType;
	ratings?: string[];
	stats?: string[];
	attrs?: string[];
	template?: string | ((props: TemplateProps) => JSX.Element | string);
	options?: { [key: string]: any };
};

export type ColTemp = Omit<MetaCol, "title" | "key" | "template"> & {
	title?: string;
	template?: string;
};

const gp = isSport("hockey") ? "GP" : "G";

const sportSpecificCols = bySport<{
	[key: string]: ColTemp;
}>({
	basketball: {
		"rating:fg": {
			cat: "Rating",
			desc: "Mid Range",
			ratings: ["fg"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "2Pt",
		},
		"rating:tp": {
			cat: "Rating",
			desc: "Three Pointers",
			ratings: ["tp"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "3Pt",
		},
		"rating:oiq": {
			cat: "Rating",
			desc: "Offensive IQ",
			ratings: ["oiq"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "oIQ",
		},
		"rating:dnk": {
			cat: "Rating",
			desc: "Dunks/Layups",
			ratings: ["dnk"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "Dnk",
		},
		"rating:drb": {
			cat: "Rating",
			desc: "Dribbling",
			ratings: ["drb"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "Drb",
		},
		"rating:ins": {
			cat: "Rating",
			desc: "Inside Scoring",
			ratings: ["ins"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "Ins",
		},
		"rating:jmp": {
			cat: "Rating",
			desc: "Jumping",
			ratings: ["jmp"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "Jmp",
		},
		"rating:ft": {
			cat: "Rating",
			desc: "Free Throws",
			ratings: ["ft"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "FT",
		},
		"rating:pss": {
			cat: "Rating",
			desc: "Passing",
			ratings: ["pss"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "Pss",
		},
		"rating:reb": {
			cat: "Rating",
			desc: "Rebounding",
			ratings: ["reb"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "Reb",
		},
		"rating:diq": {
			cat: "Rating",
			desc: "Defensive IQ",
			ratings: ["diq"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "dIQ",
		},
		"stat:2pp": {
			cat: "Stat",
			desc: "Two Point Percentage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["2pp"],
			template: "Stat",
			title: "2P%",
		},
		"stat:2p": {
			cat: "Stat",
			desc: "Two Pointers Made",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["2p"],
			template: "Stat",
			title: "2P",
		},
		"stat:2pa": {
			cat: "Stat",
			desc: "Two Pointers Attempted",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["2pa"],
			template: "Stat",
			title: "2PA",
		},
		"stat:pm": {
			cat: "Stat",
			desc: "Plus/Minus",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pm"],
			template: "Stat",
			title: "+/-",
		},
		"stat:tpp": {
			cat: "Stat",
			desc: "Three Point Percentage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["tpp"],
			template: "Stat",
			title: "3P%",
		},
		"stat:tp": {
			cat: "Stat",
			desc: "Three Pointers Made",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["tp"],
			template: "Stat",
			title: "3P",
		},
		"stat:tpa": {
			cat: "Stat",
			desc: "Three Pointers Attempted",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["tpa"],
			template: "Stat",
			title: "3PA",
		},
		"stat:tpar": {
			cat: "Stat",
			desc: "Three Point Attempt Rate (3PA / FGA)",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["tpar"],
			template: "Stat",
			title: "3PAr",
		},
		"stat:astp": {
			cat: "Stat",
			desc: "Percentage of teammate field goals a player assisted while on the floor",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["astp"],
			template: "Stat",
			title: "AST%",
		},
		"stat:ast": {
			cat: "Stat",
			desc: "Assists",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ast"],
			template: "Stat",
			title: "AST",
		},
		"stat:ba": {
			cat: "Stat",
			desc: "Blocks Against",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ba"],
			template: "Stat",
			title: "BA",
		},
		"stat:blk": {
			cat: "Stat",
			desc: "Blocks",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["blk"],
			template: "Stat",
			title: "BLK",
		},
		"stat:blkp": {
			cat: "Stat",
			desc: "Percentage of opponent two-pointers blocked",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["blkp"],
			template: "Stat",
			title: "BLK%",
		},
		"stat:drb": {
			cat: "Stat",
			desc: "Defensive Rebounds",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["drb"],
			template: "Stat",
			title: "DRB",
		},
		"stat:drbp": {
			cat: "Stat",
			desc: "Percentage of available defensive rebounds grabbed",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["drbp"],
			template: "Stat",
			title: "DRB%",
		},
		"stat:drtg": {
			cat: "Stat",
			desc: "Defensive Rating (points allowed per 100 possessions)",
			sortSequence: ["asc", "desc"],
			sortType: "number",
			stats: ["drtg"],
			template: "Stat",
			title: "DRtg",
		},
		"stat:dws": {
			cat: "Stat",
			desc: "Defensive Win Shares",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["dws"],
			template: "Stat",
			title: "DWS",
		},
		"stat:ewa": {
			cat: "Stat",
			desc: "Estimated Wins Added",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ewa"],
			template: "Stat",
			title: "EWA",
		},
		"stat:efg": {
			cat: "Stat",
			desc: "Effective Field Goal Percentage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["efg"],
			template: "Stat",
			title: "eFG%",
		},
		"stat:fgp": {
			cat: "Stat",
			desc: "Field Goal Percentage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fgp"],
			template: "Stat",
			title: "FG%",
		},
		"stat:fg": {
			cat: "Stat",
			desc: "Field Goals Made",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fg"],
			template: "Stat",
			title: "FG",
		},
		"stat:fga": {
			cat: "Stat",
			desc: "Field Goals Attempted",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fga"],
			template: "Stat",
			title: "FGA",
		},
		"stat:ftp": {
			cat: "Stat",
			desc: "Free Throw Percentage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ftp"],
			template: "Stat",
			title: "FT%",
		},
		"stat:ft": {
			cat: "Stat",
			desc: "Free Throws Made",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ft"],
			template: "Stat",
			title: "FT",
		},
		"stat:fta": {
			cat: "Stat",
			desc: "Free Throws Attempted",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fta"],
			template: "Stat",
			title: "FTA",
		},
		"stat:ftpFga": {
			cat: "Stat",
			desc: "Free Throws per Field Goal Attempted",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ftpFga"],
			template: "Stat",
			title: "FTr",
		},
		"stat:ftr": {
			cat: "Stat",
			desc: "Free Throw Attempt Rate (FTA / FGA)",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ftr"],
			template: "Stat",
			title: "FT/FGA",
		},
		"stat:gmsc": {
			cat: "Stat",
			desc: "Game Score",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["gmsc"],
			template: "Stat",
			title: "GmSc",
		},
		"stat:nrtg": {
			cat: "Stat",
			desc: "Net Rating (point differential per 100 possessions)",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["nrtg"],
			template: "Stat",
			title: "NRtg",
		},
		"stat:orb": {
			cat: "Stat",
			desc: "Offensive Rebounds",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["orb"],
			template: "Stat",
			title: "ORB",
		},
		"stat:orbp": {
			cat: "Stat",
			desc: "Percentage of available offensive rebounds grabbed",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["orbp"],
			template: "Stat",
			title: "ORB%",
		},
		"stat:ortg": {
			cat: "Stat",
			desc: "Offensive Rating (points produced/scored per 100 possessions)",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ortg"],
			template: "Stat",
			title: "ORtg",
		},
		"stat:ows": {
			cat: "Stat",
			desc: "Offensive Win Shares",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ows"],
			template: "Stat",
			title: "OWS",
		},
		"stat:pace": {
			cat: "Stat",
			desc: "Possessions Per Game",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pace"],
			template: "Stat",
			title: "Pace",
		},
		"stat:per": {
			cat: "Stat",
			desc: "Player Efficiency Rating",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["per"],
			template: "Stat",
			title: "PER",
		},
		"stat:pf": {
			cat: "Stat",
			desc: "Personal Fouls",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pf"],
			template: "Stat",
			title: "PF",
		},
		"stat:pts": {
			cat: "Stat",
			desc: "Points",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pts"],
			template: "Stat",
			title: "PTS",
		},
		"stat:stl": {
			cat: "Stat",
			desc: "Steals",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["stl"],
			template: "Stat",
			title: "STL",
		},
		"stat:stlp": {
			cat: "Stat",
			desc: "Percentage of opponent possessions ending in steals",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["stlp"],
			template: "Stat",
			title: "STL%",
		},
		"stat:tovp": {
			cat: "Stat",
			desc: "Turnovers per 100 plays",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["tovp"],
			template: "Stat",
			title: "TOV%",
		},
		"stat:trb": {
			cat: "Stat",
			desc: "Total Rebounds",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["trb"],
			template: "Stat",
			title: "TRB",
		},
		"stat:trbp": {
			cat: "Stat",
			desc: "Percentage of available rebounds grabbed",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["trbp"],
			template: "Stat",
			title: "TRB%",
		},
		"stat:tsp": {
			cat: "Stat",
			desc: "True Shooting Percentage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["tsp"],
			template: "Stat",
			title: "TS%",
		},
		"stat:tov": {
			cat: "Stat",
			desc: "Turnovers",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["tov"],
			template: "Stat",
			title: "TOV",
		},
		"stat:usgp": {
			cat: "Stat",
			desc: "Percentage of team plays used",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["usgp"],
			template: "Stat",
			title: "USG%",
		},
		"stat:ws": {
			cat: "Stat",
			desc: "Win Shares",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ws"],
			template: "Stat",
			title: "WS",
		},
		"stat:ws48": {
			cat: "Stat",
			desc: "Win Shares Per 48 Minutes",
			options: { decimals: 3 },
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ws48"],
			template: "Stat",
			title: "WS/48",
		},
		"stat:obpm": {
			cat: "Stat",
			desc: "Offensive Box Plus-Minus",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["obpm"],
			template: "Stat",
			title: "OBPM",
		},
		"stat:dbpm": {
			cat: "Stat",
			desc: "Defensive Box Plus-Minus",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["dbpm"],
			template: "Stat",
			title: "DBPM",
		},
		"stat:bpm": {
			cat: "Stat",
			desc: "Box Plus-Minus",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["bpm"],
			template: "Stat",
			title: "BPM",
		},
		"stat:vorp": {
			cat: "Stat",
			desc: "Value Over Replacement Player",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["vorp"],
			template: "Stat",
			title: "VORP",
		},
		"stat:fgAtRim": {
			cat: "Stat",
			desc: "At Rim Made",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fgAtRim"],
			template: "Stat",
			title: "FG Rim",
		},
		"stat:fgaAtRim": {
			cat: "Stat",
			desc: "At Rim Attempted",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fgaAtRim"],
			template: "Stat",
			title: "FGA Rim",
		},
		"stat:fgpAtRim": {
			cat: "Stat",
			desc: "At Rim Percentage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fgpAtRim"],
			template: "Stat",
			title: "FG% Rim",
		},
		"stat:fgLowPost": {
			cat: "Stat",
			desc: "Low Post Made",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fgLowPost"],
			template: "Stat",
			title: "FG Post",
		},
		"stat:fgaLowPost": {
			cat: "Stat",
			desc: "Low Post Attempted",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fgaLowPost"],
			template: "Stat",
			title: "FGA Post",
		},
		"stat:fgpLowPost": {
			cat: "Stat",
			desc: "Low Post Percentage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fgpLowPost"],
			template: "Stat",
			title: "FG% Post",
		},
		"stat:fgMidRange": {
			cat: "Stat",
			desc: "Mid Range Made",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fgMidRange"],
			template: "Stat",
			title: "FG Mid",
		},
		"stat:fgaMidRange": {
			cat: "Stat",
			desc: "Mid Range Attempted",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fgaMidRange"],
			template: "Stat",
			title: "FGA Mid",
		},
		"stat:fgpMidRange": {
			cat: "Stat",
			desc: "Mid Range Percentage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fgpMidRange"],
			template: "Stat",
			title: "FG% Mid",
		},
		"stat:dd": {
			cat: "Stat",
			desc: "Double Doubles",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["dd"],
			template: "Stat",
			title: "DD",
		},
		"stat:td": {
			cat: "Stat",
			desc: "Triple Doubles",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["td"],
			template: "Stat",
			title: "TD",
		},
		"stat:qd": {
			cat: "Stat",
			desc: "Quadruple Doubles",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["qd"],
			template: "Stat",
			title: "QD",
		},
		"stat:fxf": {
			cat: "Stat",
			desc: "Five by Fives",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fxf"],
			template: "Stat",
			title: "5x5",
		},
	},
	football: {
		"pos:QB": {
			cat: "Position",
			desc: "Quarterback",
			sortType: "number",
			title: "QB",
		},
		"pos:RB": {
			cat: "Position",
			desc: "Running Back",
			sortType: "number",
			title: "RB",
		},
		"pos:WR": {
			cat: "Position",
			desc: "Wide Receiver",
			sortType: "number",
			title: "WR",
		},
		"pos:TE": {
			cat: "Position",
			desc: "Tight End",
			sortType: "number",
			title: "TE",
		},
		"pos:OL": {
			cat: "Position",
			desc: "Offensive Lineman",
			sortType: "number",
			title: "OL",
		},
		"pos:DL": {
			cat: "Position",
			desc: "Defensive Lineman",
			sortType: "number",
			title: "DL",
		},
		"pos:LB": {
			cat: "Position",
			desc: "Linebacker",
			sortType: "number",
			title: "LB",
		},
		"pos:CB": {
			cat: "Position",
			desc: "Cornerback",
			sortType: "number",
			title: "CB",
		},
		"pos:S": {
			cat: "Position",
			desc: "Safety",
			sortType: "number",
			title: "S",
		},
		"pos:K": {
			cat: "Position",
			desc: "Kicker",
			sortType: "number",
			title: "K",
		},
		"pos:P": {
			cat: "Position",
			desc: "Punter",
			sortType: "number",
			title: "P",
		},
		"rating:thv": {
			cat: "Rating",
			desc: "Throwing Vision",
			ratings: ["thv"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "ThV",
		},
		"rating:thp": {
			cat: "Rating",
			desc: "Throwing Power",
			ratings: ["thp"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "ThP",
		},
		"rating:tha": {
			cat: "Rating",
			desc: "Throwing Accuracy",
			ratings: ["tha"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "ThA",
		},
		"rating:bsc": {
			cat: "Rating",
			desc: "Ball Security",
			ratings: ["bsc"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "BSc",
		},
		"rating:elu": {
			cat: "Rating",
			desc: "Elusiveness",
			ratings: ["elu"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "Elu",
		},
		"rating:rtr": {
			cat: "Rating",
			desc: "Route Running",
			ratings: ["rtr"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "RtR",
		},
		"rating:hnd": {
			cat: "Rating",
			desc: "Hands",
			ratings: ["hnd"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "Hnd",
		},
		"rating:rbk": {
			cat: "Rating",
			desc: "Run Blocking",
			ratings: ["rbk"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "RBk",
		},
		"rating:pbk": {
			cat: "Rating",
			desc: "Pass Blocking",
			ratings: ["pbk"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PBk",
		},
		"rating:pcv": {
			cat: "Rating",
			desc: "Pass Coverage",
			ratings: ["pcv"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PCv",
		},
		"rating:tck": {
			cat: "Rating",
			desc: "Tackling",
			ratings: ["tck"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "Tck",
		},
		"rating:prs": {
			cat: "Rating",
			desc: "Pass Rushing",
			ratings: ["prs"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PRs",
		},
		"rating:rns": {
			cat: "Rating",
			desc: "Run Stopping",
			ratings: ["rns"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "RnS",
		},
		"rating:kpw": {
			cat: "Rating",
			desc: "Kicking Power",
			ratings: ["kpw"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "KPw",
		},
		"rating:kac": {
			cat: "Rating",
			desc: "Kicking Accuracy",
			ratings: ["kac"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "KAc",
		},
		"rating:ppw": {
			cat: "Rating",
			desc: "Punting Power",
			ratings: ["ppw"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PPw",
		},
		"rating:pac": {
			cat: "Rating",
			desc: "Punting Accuracy",
			ratings: ["pac"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PAc",
		},
		"rating:ovrQB": {
			cat: "Rating",
			desc: "Overall Rating (QB)",
			ratings: ["ovrQB"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "OvrQB",
		},
		"rating:ovrRB": {
			cat: "Rating",
			desc: "Overall Rating (RB)",
			ratings: ["ovrRB"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "OvrRB",
		},
		"rating:ovrWR": {
			cat: "Rating",
			desc: "Overall Rating (WR)",
			ratings: ["ovrWR"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "OvrWR",
		},
		"rating:ovrTE": {
			cat: "Rating",
			desc: "Overall Rating (TE)",
			ratings: ["ovrTE"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "OvrTE",
		},
		"rating:ovrOL": {
			cat: "Rating",
			desc: "Overall Rating (OL)",
			ratings: ["ovrOL"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "OvrOL",
		},
		"rating:ovrDL": {
			cat: "Rating",
			desc: "Overall Rating (DL)",
			ratings: ["ovrDL"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "OvrDL",
		},
		"rating:ovrLB": {
			cat: "Rating",
			desc: "Overall Rating (LB)",
			ratings: ["ovrLB"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "OvrLB",
		},
		"rating:ovrCB": {
			cat: "Rating",
			desc: "Overall Rating (CB)",
			ratings: ["ovrCB"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "OvrCB",
		},
		"rating:ovrS": {
			cat: "Rating",
			desc: "Overall Rating (S)",
			ratings: ["ovrS"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "OvrS",
		},
		"rating:ovrK": {
			cat: "Rating",
			desc: "Overall Rating (K)",
			ratings: ["ovrK"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "OvrK",
		},
		"rating:ovrP": {
			cat: "Rating",
			desc: "Overall Rating (P)",
			ratings: ["ovrP"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "OvrP",
		},
		"rating:ovrKR": {
			cat: "Rating",
			desc: "Overall Rating (KR)",
			ratings: ["ovrKR"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "OvrKR",
		},
		"rating:ovrPR": {
			cat: "Rating",
			desc: "Overall Rating (PR)",
			ratings: ["ovrPR"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "OvrPR",
		},
		"rating:potQB": {
			cat: "Rating",
			desc: "Potential Rating (QB)",
			ratings: ["potQB"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PotQB",
		},
		"rating:potRB": {
			cat: "Rating",
			desc: "Potential Rating (RB)",
			ratings: ["potRB"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PotRB",
		},
		"rating:potWR": {
			cat: "Rating",
			desc: "Potential Rating (WR)",
			ratings: ["potWR"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PotWR",
		},
		"rating:potTE": {
			cat: "Rating",
			desc: "Potential Rating (TE)",
			ratings: ["potTE"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PotTE",
		},
		"rating:potOL": {
			cat: "Rating",
			desc: "Potential Rating (OL)",
			ratings: ["potOL"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PotOL",
		},
		"rating:potDL": {
			cat: "Rating",
			desc: "Potential Rating (DL)",
			ratings: ["potDL"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PotDL",
		},
		"rating:potLB": {
			cat: "Rating",
			desc: "Potential Rating (LB)",
			ratings: ["potLB"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PotLB",
		},
		"rating:potCB": {
			cat: "Rating",
			desc: "Potential Rating (CB)",
			ratings: ["potCB"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PotCB",
		},
		"rating:potS": {
			cat: "Rating",
			desc: "Potential Rating (S)",
			ratings: ["potS"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PotS",
		},
		"rating:potK": {
			cat: "Rating",
			desc: "Potential Rating (K)",
			ratings: ["potK"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PotK",
		},
		"rating:potP": {
			cat: "Rating",
			desc: "Potential Rating (P)",
			ratings: ["potP"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PotP",
		},
		"rating:potKR": {
			cat: "Rating",
			desc: "Potential Rating (KR)",
			ratings: ["potKR"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PotKR",
		},
		"rating:potPR": {
			cat: "Rating",
			desc: "Potential Rating (PR)",
			ratings: ["potPR"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PotPR",
		},
		"stat:fmb": {
			cat: "Stat",
			desc: "Fumbles",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fmb"],
			template: "Stat",
			title: "Fmb",
		},
		"stat:fmbLost": {
			cat: "Stat",
			desc: "Fumbles Lost",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fmbLost"],
			template: "Stat",
			title: "FL",
		},
		"stat:fp": {
			cat: "Stat",
			desc: "Fantasy Points",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fp"],
			template: "Stat",
			title: "FP",
		},
		"stat:pssCmp": {
			cat: "Stat",
			desc: "Completions",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pssCmp"],
			template: "Stat",
			title: "Cmp",
		},
		"stat:pss": {
			cat: "Stat",
			desc: "Passing Attempts",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pss"],
			template: "Stat",
			title: "Att",
		},
		"stat:pssYds": {
			cat: "Stat",
			desc: "Passing Yards",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pssYds"],
			template: "Stat",
			title: "Yds",
		},
		"stat:pssTD": {
			cat: "Stat",
			desc: "Passing Touchdowns",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pssTD"],
			template: "Stat",
			title: "TD",
		},
		"stat:pssInt": {
			cat: "Stat",
			desc: "Interceptions",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pssInt"],
			template: "Stat",
			title: "Int",
		},
		"stat:pssLng": {
			cat: "Stat",
			desc: "Longest Pass",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pssLng"],
			template: "Stat",
			title: "Lng",
		},
		"stat:pssSk": {
			cat: "Stat",
			desc: "Times Sacked",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pssSk"],
			template: "Stat",
			title: "Sk",
		},
		"stat:pssSkYds": {
			cat: "Stat",
			desc: "Yards lost due to sacks",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pssSkYds"],
			template: "Stat",
			title: "Yds",
		},
		"stat:rus": {
			cat: "Stat",
			desc: "Rushing Attempts",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["rus"],
			template: "Stat",
			title: "Rush",
		},
		"stat:rusYds": {
			cat: "Stat",
			desc: "Rushing Yards",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["rusYds"],
			template: "Stat",
			title: "Yds",
		},
		"stat:rusTD": {
			cat: "Stat",
			desc: "Rushing Touchdowns",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["rusTD"],
			template: "Stat",
			title: "TD",
		},
		"stat:rusLng": {
			cat: "Stat",
			desc: "Longest Run",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["rusLng"],
			template: "Stat",
			title: "Lng",
		},
		"stat:tgt": {
			cat: "Stat",
			desc: "Targets",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["tgt"],
			template: "Stat",
			title: "Tgt",
		},
		"stat:rec": {
			cat: "Stat",
			desc: "Receptions",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["rec"],
			template: "Stat",
			title: "Rec",
		},
		"stat:recYds": {
			cat: "Stat",
			desc: "Receiving Yards",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["recYds"],
			template: "Stat",
			title: "Yds",
		},
		"stat:recTD": {
			cat: "Stat",
			desc: "Receiving Touchdowns",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["recTD"],
			template: "Stat",
			title: "TD",
		},
		"stat:recLng": {
			cat: "Stat",
			desc: "Longest Reception",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["recLng"],
			template: "Stat",
			title: "Lng",
		},
		"stat:pr": {
			cat: "Stat",
			desc: "Punt Returns",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pr"],
			template: "Stat",
			title: "PR",
		},
		"stat:prYds": {
			cat: "Stat",
			desc: "Punt Return Yards",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["prYds"],
			template: "Stat",
			title: "Yds",
		},
		"stat:prTD": {
			cat: "Stat",
			desc: "Punts returned for touchdowns",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["prTD"],
			template: "Stat",
			title: "TD",
		},
		"stat:prLng": {
			cat: "Stat",
			desc: "Longest Punt Return",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["prLng"],
			template: "Stat",
			title: "Lng",
		},
		"stat:kr": {
			cat: "Stat",
			desc: "Kickoff Returns",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["kr"],
			template: "Stat",
			title: "KR",
		},
		"stat:krYds": {
			cat: "Stat",
			template: "Stat",
			stats: ["krYds"],
			desc: "Kickoff Return Yards",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			title: "Yds",
		},
		"stat:krTD": {
			cat: "Stat",
			desc: "Kickoffs returned for touchdowns",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["krTD"],
			template: "Stat",
			title: "TD",
		},
		"stat:krLng": {
			cat: "Stat",
			desc: "Longest Kickoff Return",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["krLng"],
			template: "Stat",
			title: "Lng",
		},
		"stat:defInt": {
			cat: "Stat",
			desc: "Interceptions",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["defInt"],
			template: "Stat",
			title: "Int",
		},
		"stat:defIntYds": {
			cat: "Stat",
			desc: "Yards interceptions were returned for",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["defIntYds"],
			template: "Stat",
			title: "Yds",
		},
		"stat:defIntTD": {
			cat: "Stat",
			desc: "Interceptions returned for touchdowns",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["defIntTD"],
			template: "Stat",
			title: "TD",
		},
		"stat:defIntLng": {
			cat: "Stat",
			desc: "Longest Interception Return",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["defIntLng"],
			template: "Stat",
			title: "Lng",
		},
		"stat:defPssDef": {
			cat: "Stat",
			desc: "Passes Defended",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["defPssDef"],
			template: "Stat",
			title: "PD",
		},
		"stat:defFmbFrc": {
			cat: "Stat",
			desc: "Forced Fumbles",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["defFmbFrc"],
			template: "Stat",
			title: "FF",
		},
		"stat:defFmbRec": {
			cat: "Stat",
			desc: "Fumbles Recovered",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["defFmbRec"],
			template: "Stat",
			title: "FR",
		},
		"stat:defFmbYds": {
			cat: "Stat",
			desc: "Yards fumbles were returned for",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["defFmbYds"],
			template: "Stat",
			title: "Yds",
		},
		"stat:defFmbTD": {
			cat: "Stat",
			desc: "Fumbles returned for touchdowns",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["defFmbTD"],
			template: "Stat",
			title: "TD",
		},
		"stat:defFmbLng": {
			cat: "Stat",
			desc: "Longest Fumble Return",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["defFmbLng"],
			template: "Stat",
			title: "Lng",
		},
		"stat:defSk": {
			cat: "Stat",
			desc: "Sacks",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["defSk"],
			template: "Stat",
			title: "Sk",
		},
		"stat:defTckSolo": {
			cat: "Stat",
			desc: "Solo Tackles",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["defTckSolo"],
			template: "Stat",
			title: "Solo",
		},
		"stat:defTckAst": {
			cat: "Stat",
			desc: "Assists On Tackles",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["defTckAst"],
			template: "Stat",
			title: "Ast",
		},
		"stat:defTckLoss": {
			cat: "Stat",
			desc: "Tackes For Loss",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["defTckLoss"],
			template: "Stat",
			title: "TFL",
		},
		"stat:defSft": {
			cat: "Stat",
			desc: "Safeties Scored",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["defSft"],
			template: "Stat",
			title: "Sfty",
		},
		"stat:fg0": {
			cat: "Stat",
			desc: "Field Goals Made, 19 yards and under",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fg0"],
			template: "Stat",
			title: "FG10",
		},
		"stat:fga0": {
			cat: "Stat",
			desc: "Field Goals Attempted, 19 yards and under",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fga0"],
			template: "Stat",
			title: "FGA10",
		},
		"stat:fg20": {
			cat: "Stat",
			desc: "Field Goals Made, 20-29 yards",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fg20"],
			template: "Stat",
			title: "FG20",
		},
		"stat:fga20": {
			cat: "Stat",
			desc: "Field Goals Attempted, 20-29 yards",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fga20"],
			template: "Stat",
			title: "FGA20",
		},
		"stat:fg30": {
			cat: "Stat",
			desc: "Field Goals Made, 30-39 yards",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fg30"],
			template: "Stat",
			title: "FG30",
		},
		"stat:fga30": {
			cat: "Stat",
			desc: "Field Goals Attempted, 30-39 yards",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fga30"],
			template: "Stat",
			title: "FGA30",
		},
		"stat:fg40": {
			cat: "Stat",
			desc: "Field Goals Made, 40-49 yards",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fg40"],
			template: "Stat",
			title: "FG40",
		},
		"stat:fga40": {
			cat: "Stat",
			desc: "Field Goals Attempted, 40-49 yards",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fga40"],
			template: "Stat",
			title: "FGA40",
		},
		"stat:fg50": {
			cat: "Stat",
			desc: "Field Goals Made, 50+ yards",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fg50"],
			template: "Stat",
			title: "FG50",
		},
		"stat:fga50": {
			cat: "Stat",
			desc: "Field Goals Attempted, 50+ yards",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fga50"],
			template: "Stat",
			title: "FGA50",
		},
		"stat:fgLng": {
			cat: "Stat",
			desc: "Longest Field Goal",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fgLng"],
			template: "Stat",
			title: "Lng",
		},
		"stat:xp": {
			cat: "Stat",
			desc: "Extra Points Made",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["xp"],
			template: "Stat",
			title: "XPM",
		},
		"stat:xpa": {
			cat: "Stat",
			desc: "Extra Points Attempted",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["xpa"],
			template: "Stat",
			title: "XPA",
		},
		"stat:pnt": {
			cat: "Stat",
			desc: "Times Punted",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pnt"],
			template: "Stat",
			title: "Pnt",
		},
		"stat:pntYds": {
			cat: "Stat",
			desc: "Total Punt Yardage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pntYds"],
			template: "Stat",
			title: "Yds",
		},
		"stat:pntLng": {
			cat: "Stat",
			desc: "Longest Punt",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pntLng"],
			template: "Stat",
			title: "Lng",
		},
		"stat:pntBlk": {
			cat: "Stat",
			desc: "Times Punts Blocked",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pntBlk"],
			template: "Stat",
			title: "Blk",
		},
		"stat:pen": {
			cat: "Stat",
			desc: "Penalties",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pen"],
			template: "Stat",
			title: "Pen",
		},
		"stat:penYds": {
			cat: "Stat",
			desc: "Penalty Yards",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["penYds"],
			template: "Stat",
			title: "Yds",
		},
		"stat:cmpPct": {
			cat: "Stat",
			desc: "Completion Percentage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["cmpPct"],
			template: "Stat",
			title: "Pct",
		},
		"stat:qbRat": {
			cat: "Stat",
			desc: "Quarterback Rating",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["qbRat"],
			template: "Stat",
			title: "QBRat",
		},
		"stat:rusYdsPerAtt": {
			cat: "Stat",
			desc: "Rushing Yards Per Attempt",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["rusYdsPerAtt"],
			template: "Stat",
			title: "Y/A",
		},
		"stat:recYdsPerAtt": {
			cat: "Stat",
			desc: "Yards Per Catch",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["recYdsPerAtt"],
			template: "Stat",
			title: "Y/A",
		},
		"stat:fg": {
			cat: "Stat",
			desc: "Field Goals Made",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fg"],
			template: "Stat",
			title: "FGM",
		},
		"stat:fga": {
			cat: "Stat",
			desc: "Field Goals Attempted",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fga"],
			template: "Stat",
			title: "FGA",
		},
		"stat:fgPct": {
			cat: "Stat",
			desc: "Field Goal Percentage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fgPct"],
			template: "Stat",
			title: "Pct",
		},
		"stat:xpPct": {
			cat: "Stat",
			desc: "Extra Point Percentage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["xpPct"],
			template: "Stat",
			title: "Pct",
		},
		"stat:kickingPts": {
			cat: "Stat",
			desc: "Kicking Points",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["kickingPts"],
			template: "Stat",
			title: "Pts",
		},
		"stat:pntYdsPerAtt": {
			cat: "Stat",
			desc: "Yards Per Punt",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pntYdsPerAtt"],
			template: "Stat",
			title: "Y/A",
		},
		"stat:pntTB": {
			cat: "Stat",
			desc: "Punt Touchbacks",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pntTB"],
			template: "Stat",
			title: "TB",
		},
		"stat:pntIn20": {
			cat: "Stat",
			desc: "Punts Inside 20",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pntIn20"],
			template: "Stat",
			title: "In20",
		},
		"stat:krYdsPerAtt": {
			cat: "Stat",
			desc: "Yards Per Kick Return",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["krYdsPerAtt"],
			template: "Stat",
			title: "Y/A",
		},
		"stat:prYdsPerAtt": {
			cat: "Stat",
			desc: "Yards Per Punt Return",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["prYdsPerAtt"],
			template: "Stat",
			title: "Y/A",
		},
		"stat:defTck": {
			cat: "Stat",
			desc: "Total Tackles",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["defTck"],
			template: "Stat",
			title: "Tck",
		},
		"stat:keyStats": {
			cat: "Stat",
			desc: "Key Stats",
			sortSequence: ["desc", "asc"],
			sortType: "string",
			stats: ["keyStats"],
			template: "Stat",
			title: "Stats",
		},
		"stat:pts": {
			cat: "Stat",
			desc: "",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pts"],
			template: "Stat",
			title: "Pts",
		},
		"stat:yds": {
			cat: "Stat",
			desc: "Offensive Yards",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["yds"],
			template: "Stat",
			title: "Yds",
		},
		"stat:ply": {
			cat: "Stat",
			desc: "Plays",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ply"],
			template: "Stat",
			title: "Ply",
		},
		"stat:ydsPerPlay": {
			cat: "Stat",
			desc: "Yards Per Play",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ydsPerPlay"],
			template: "Stat",
			title: "Y/P",
		},
		"stat:tov": {
			cat: "Stat",
			desc: "Turnovers",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["tov"],
			template: "Stat",
			title: "TO",
		},
		"stat:drives": {
			cat: "Stat",
			desc: "Number of Drives",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["drives"],
			template: "Stat",
			title: "#Dr",
		},
		"stat:drivesScoringPct": {
			cat: "Stat",
			desc: "Percentage of drives ending in a score",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["drivesScoringPct"],
			template: "Stat",
			title: "Sc%",
		},
		"stat:drivesTurnoverPct": {
			cat: "Stat",
			desc: "Percentage of drives ending in a turnover",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["drivesTurnoverPct"],
			template: "Stat",
			title: "TO%",
		},
		"stat:avgFieldPosition": {
			cat: "Stat",
			desc: "Average Starting Field Position",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["avgFieldPosition"],
			template: "Stat",
			title: "Start",
		},
		"stat:timePerDrive": {
			cat: "Stat",
			desc: "Time Per Drive (minutes)",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["timePerDrive"],
			template: "Stat",
			title: "Tm/D",
		},
		"stat:playsPerDrive": {
			cat: "Stat",
			desc: "Number of Plays Per Drive",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["playsPerDrive"],
			template: "Stat",
			title: "Ply/D",
		},
		"stat:ydsPerDrive": {
			cat: "Stat",
			desc: "Yards Per Drive",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ydsPerDrive"],
			template: "Stat",
			title: "Y/D",
		},
		"stat:ptsPerDrive": {
			cat: "Stat",
			desc: "Points Per Drive",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ptsPerDrive"],
			template: "Stat",
			title: "Pts/D",
		},
		"stat:qbRec": {
			cat: "Stat",
			desc: "Record as primary QB",
			sortSequence: ["desc", "asc"],
			sortType: "record",
			stats: ["qbRec"],
			template: "Stat",
			title: "QBRec",
		},
		"stat:qbW": {
			cat: "Stat",
			desc: "Wins as primary QB",
			sortSequence: ["desc", "asc"],
			sortType: "record",
			stats: ["qbW"],
			template: "Stat",
			title: "QBW",
		},
		"stat:qbL": {
			cat: "Stat",
			desc: "Losses as primary QB",
			sortSequence: ["desc", "asc"],
			sortType: "record",
			stats: ["qbL"],
			template: "Stat",
			title: "QBL",
		},
		"stat:qbT": {
			cat: "Stat",
			desc: "Ties as primary QB",
			sortSequence: ["desc", "asc"],
			sortType: "record",
			stats: ["qbT"],
			template: "Stat",
			title: "QBT",
		},
		"stat:qbOTL": {
			cat: "Stat",
			desc: "Overtime losses as primary QB",
			sortSequence: ["desc", "asc"],
			sortType: "record",
			stats: ["qbOTL"],
			template: "Stat",
			title: "QBOTL",
		},
		"stat:pssTDPct": {
			cat: "Stat",
			desc: "Percentage of passes that result in touchdowns",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pssTDPct"],
			template: "Stat",
			title: "TD%",
		},
		"stat:pssIntPct": {
			cat: "Stat",
			desc: "Percentage of passes that result in interceptions",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pssIntPct"],
			template: "Stat",
			title: "Int%",
		},
		"stat:pssYdsPerAtt": {
			cat: "Stat",
			desc: "Pass Yards Per Attempt",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pssYdsPerAtt"],
			template: "Stat",
			title: "Y/A",
		},
		"stat:pssAdjYdsPerAtt": {
			cat: "Stat",
			desc: "Adjusted Pass Yards Per Attempt ((yds + 20 * TD - 45 * int) / att)",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pssAdjYdsPerAtt"],
			template: "Stat",
			title: "AY/A",
		},
		"stat:pssYdsPerCmp": {
			cat: "Stat",
			desc: "Pass Yards Per Completion",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pssYdsPerCmp"],
			template: "Stat",
			title: "Y/C",
		},
		"stat:pssYdsPerGame": {
			cat: "Stat",
			desc: "Pass Yards Per Game",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pssYdsPerGame"],
			template: "Stat",
			title: "Y/G",
		},
		"stat:pssNetYdsPerAtt": {
			cat: "Stat",
			desc: "Net Pass Yards Per Attempt (passes and sacks)",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pssNetYdsPerAtt"],
			template: "Stat",
			title: "NY/A",
		},
		"stat:pssAdjNetYdsPerAtt": {
			cat: "Stat",
			desc: "Adjusted Net Pass Yards Per Attempt ((yds + 20 * TD - 45 * int - skYds) / (att + sk))",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pssAdjNetYdsPerAtt"],
			template: "Stat",
			title: "ANY/A",
		},
		"stat:pssSkPct": {
			cat: "Stat",
			desc: "Percentage of times sacked when attempting a pass",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pssSkPct"],
			template: "Stat",
			title: "Sk%",
		},
		"stat:rusYdsPerGame": {
			cat: "Stat",
			desc: "Rushing Yards Per Game",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["rusYdsPerGame"],
			template: "Stat",
			title: "Y/G",
		},
		"stat:rusPerGame": {
			cat: "Stat",
			desc: "Rushing Attempts Per Game",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["rusPerGame"],
			template: "Stat",
			title: "A/G",
		},
		"stat:recYdsPerRec": {
			cat: "Stat",
			desc: "Yards Per Reception",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["recYdsPerRec"],
			template: "Stat",
			title: "Y/R",
		},
		"stat:recPerGame": {
			cat: "Stat",
			desc: "Receptions Per Game",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["recPerGame"],
			template: "Stat",
			title: "R/G",
		},
		"stat:recYdsPerGame": {
			cat: "Stat",
			desc: "Receiving Yards Per Game",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["recYdsPerGame"],
			template: "Stat",
			title: "Y/G",
		},
		"stat:recCatchPct": {
			cat: "Stat",
			desc: "Catch Percentage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["recCatchPct"],
			template: "Stat",
			title: "Ctch%",
		},
		"stat:touches": {
			cat: "Stat",
			desc: "Touches (Rushing Attempts And Receptions)",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["touches"],
			template: "Stat",
			title: "Tch",
		},
		"stat:ydsPerTouch": {
			cat: "Stat",
			desc: "Yards Per Touch",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ydsPerTouch"],
			template: "Stat",
			title: "Y/Tch",
		},
		"stat:ydsFromScrimmage": {
			cat: "Stat",
			desc: "Total Rushing and Receiving Yards From Scrimmage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ydsFromScrimmage"],
			template: "Stat",
			title: "YScm",
		},
		"stat:rusRecTD": {
			cat: "Stat",
			desc: "Total Rushing and Receiving Touchdowns",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["rusRecTD"],
			template: "Stat",
			title: "RRTD",
		},
		"stat:allPurposeYds": {
			cat: "Stat",
			desc: "All Purpose Yards (Rushing, Receiving, and Kick/Punt/Fumble/Interception Returns)",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["allPurposeYds"],
			template: "Stat",
			title: "APY",
		},
		"stat:av": {
			cat: "Stat",
			desc: "Approximate Value",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["av"],
			template: "Stat",
			title: "AV",
		},
		"stat:avPerPlayer": {
			cat: "Stat",
			desc: "Approximate Value Per Player",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["avPerPlayer"],
			template: "Stat",
			title: "AV/Player",
		},
	},
	hockey: {
		"pos:C": {
			cat: "Position",
			desc: "Center",
			sortType: "number",
			title: "C",
		},
		"pos:W": {
			cat: "Position",
			desc: "Wing",
			sortType: "number",
			title: "W",
		},
		"pos:D": {
			cat: "Position",
			desc: "Defenseman",
			sortType: "number",
			title: "D",
		},
		"pos:G": {
			cat: "Position",
			desc: "Goalie",
			sortType: "number",
			title: "G",
		},
		"rating:pss": {
			cat: "Rating",
			desc: "Passing",
			ratings: ["pss"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "Pss",
		},
		"rating:wst": {
			cat: "Rating",
			desc: "Wristshot",
			ratings: ["wst"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "Wst",
		},
		"rating:sst": {
			cat: "Rating",
			desc: "Slapshot",
			ratings: ["sst"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "Sst",
		},
		"rating:stk": {
			cat: "Rating",
			desc: "Stickhandling",
			ratings: ["stk"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "Stk",
		},
		"rating:oiq": {
			cat: "Rating",
			desc: "Offensive IQ",
			ratings: ["oiq"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "oIQ",
		},
		"rating:chk": {
			cat: "Rating",
			desc: "Checking",
			ratings: ["chk"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "Chk",
		},
		"rating:blk": {
			cat: "Rating",
			desc: "Shot Blocking",
			ratings: ["blk"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "Blk",
		},
		"rating:fcf": {
			cat: "Rating",
			desc: "Faceoffs",
			ratings: ["fcf"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "Fcf",
		},
		"rating:diq": {
			cat: "Rating",
			desc: "Defensive IQ",
			ratings: ["diq"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "dIQ",
		},
		"rating:glk": {
			cat: "Rating",
			desc: "Goalkeeping",
			ratings: ["glk"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "Glk",
		},
		"rating:ovrC": {
			cat: "Rating",
			desc: "Overall Rating (Center)",
			ratings: ["ovrC"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "OvrC",
		},
		"rating:ovrW": {
			cat: "Rating",
			desc: "Overall Rating (Winger)",
			ratings: ["ovrW"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "OvrW",
		},
		"rating:ovrD": {
			cat: "Rating",
			desc: "Overall Rating (Defenseman)",
			ratings: ["ovrD"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "OvrD",
		},
		"rating:ovrG": {
			cat: "Rating",
			desc: "Overall Rating (Goalie)",
			ratings: ["ovrG"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "OvrG",
		},
		"rating:potC": {
			cat: "Rating",
			desc: "Potential Rating (Center)",
			ratings: ["potC"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PotC",
		},
		"rating:potW": {
			cat: "Rating",
			desc: "Potential Rating (Winger)",
			ratings: ["potW"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PotW",
		},
		"rating:potD": {
			cat: "Rating",
			desc: "Potential Rating (Defenseman)",
			ratings: ["potD"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PotD",
		},
		"rating:potG": {
			cat: "Rating",
			desc: "Potential Rating (Goalie)",
			ratings: ["potG"],
			sortSequence: ["desc", "asc"],
			sortType: "number",
			template: "Rating",
			title: "PotG",
		},
		"stat:gpGoalie": {
			cat: "Stat",
			desc: "Games Played (Goalie)",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["gpGoalie"],
			template: "Stat",
			title: gp,
		},
		"stat:gpSkater": {
			cat: "Stat",
			desc: "Games Played (Skater)",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["gpSkater"],
			template: "Stat",
			title: gp,
		},
		"stat:pm": {
			cat: "Stat",
			desc: "Plus/Minus",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pm"],
			template: "Stat",
			title: "+/-",
		},
		"stat:pim": {
			cat: "Stat",
			desc: "Penalty Minutes",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pim"],
			template: "Stat",
			title: "PIM",
		},
		"stat:evG": {
			cat: "Stat",
			desc: "Even Strength Goals",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["evG"],
			template: "Stat",
			title: "evG",
		},
		"stat:ppG": {
			cat: "Stat",
			desc: "Power Play Goals",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ppG"],
			template: "Stat",
			title: "ppG",
		},
		"stat:shG": {
			cat: "Stat",
			desc: "Short-Handed Goals",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["shG"],
			template: "Stat",
			title: "shG",
		},
		"stat:gwG": {
			cat: "Stat",
			desc: "Game Winning Goals",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["gwG"],
			template: "Stat",
			title: "gwG",
		},
		"stat:evA": {
			cat: "Stat",
			desc: "Even Strength Assists",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["evA"],
			template: "Stat",
			title: "evA",
		},
		"stat:ppA": {
			cat: "Stat",
			desc: "Power Play Assists",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ppA"],
			template: "Stat",
			title: "ppA",
		},
		"stat:shA": {
			cat: "Stat",
			desc: "Short-Handed Assists",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["shA"],
			template: "Stat",
			title: "shA",
		},
		"stat:gwA": {
			cat: "Stat",
			desc: "Game Winning Assists",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["gwA"],
			template: "Stat",
			title: "gwA",
		},
		"stat:s": {
			cat: "Stat",
			desc: "Shots on Goal",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["s"],
			template: "Stat",
			title: "S",
		},
		"stat:tsa": {
			cat: "Stat",
			desc: "Total Shots Attempted",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["tsa"],
			template: "Stat",
			title: "TSA",
		},
		"stat:fow": {
			cat: "Stat",
			desc: "Faceoff Wins",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fow"],
			template: "Stat",
			title: "FOW",
		},
		"stat:fol": {
			cat: "Stat",
			desc: "Faceoff Losses",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["fol"],
			template: "Stat",
			title: "FOL",
		},
		"stat:foPct": {
			cat: "Stat",
			desc: "Faceoff Win Percentage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["foPct"],
			template: "Stat",
			title: "FO%",
		},
		"stat:blk": {
			cat: "Stat",
			desc: "Blocks",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["blk"],
			template: "Stat",
			title: "BLK",
		},
		"stat:hit": {
			cat: "Stat",
			desc: "Hits",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["hit"],
			template: "Stat",
			title: "HIT",
		},
		"stat:tk": {
			cat: "Stat",
			desc: "Takeaways",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["tk"],
			template: "Stat",
			title: "TK",
		},
		"stat:gv": {
			cat: "Stat",
			desc: "Giveaways",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["gv"],
			template: "Stat",
			title: "GV",
		},
		"stat:ga": {
			cat: "Stat",
			desc: "Goals Against",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ga"],
			template: "Stat",
			title: "GA",
		},
		"stat:sv": {
			cat: "Stat",
			desc: "Saves",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["sv"],
			template: "Stat",
			title: "SV",
		},
		"stat:so": {
			cat: "Stat",
			desc: "Shutouts",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["so"],
			template: "Stat",
			title: "SO",
		},
		"stat:g": {
			cat: "Stat",
			desc: "Goals",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["g"],
			template: "Stat",
			title: "G",
		},
		"stat:a": {
			cat: "Stat",
			desc: "Assists",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["a"],
			template: "Stat",
			title: "A",
		},
		"stat:pts": {
			cat: "Stat",
			desc: "Points",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["pts"],
			template: "Stat",
			title: "PTS",
		},
		"stat:sPct": {
			cat: "Stat",
			desc: "Shooting Percentage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["sPct"],
			template: "Stat",
			title: "S%",
		},
		"stat:svPct": {
			cat: "Stat",
			desc: "Save Percentage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["svPct"],
			template: "Stat",
			title: "SV%",
		},
		"stat:sa": {
			cat: "Stat",
			desc: "Shots Against",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["sa"],
			template: "Stat",
			title: "SA",
		},
		"stat:gaa": {
			cat: "Stat",
			desc: "Goals Against Average",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["gaa"],
			template: "Stat",
			title: "GAA",
		},
		"stat:keyStats": {
			cat: "Stat",
			desc: "Key Stats",
			sortSequence: ["desc", "asc"],
			sortType: "string",
			stats: ["keyStats"],
			template: "Stat",
			title: "Stats",
		},
		"stat:ps": {
			cat: "Stat",
			desc: "Point Shares",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ps"],
			template: "Stat",
			title: "PS",
		},
		"stat:psPerPlayer": {
			cat: "Stat",
			desc: "Point Shares Per Player",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["psPerPlayer"],
			template: "Stat",
			title: "PS/Player",
		},
		"stat:ops": {
			cat: "Stat",
			desc: "Offensive Point Shares",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ops"],
			template: "Stat",
			title: "OPS",
		},
		"stat:dps": {
			cat: "Stat",
			desc: "Defensive Point Shares",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["dps"],
			template: "Stat",
			title: "DPS",
		},
		"stat:gps": {
			cat: "Stat",
			desc: "Goalie Point Shares",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["gps"],
			template: "Stat",
			title: "GPS",
		},
		"stat:gc": {
			cat: "Stat",
			desc: "Goals Created",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["gc"],
			template: "Stat",
			title: "GC",
		},
		"stat:amin": {
			cat: "Stat",
			desc: "Average Time On Ice",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["amin"],
			template: "Stat",
			title: "ATOI",
		},
		"stat:ppMin": {
			cat: "Stat",
			desc: "Power Play Time On Ice",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ppMin"],
			template: "Stat",
			title: "ppTOI",
		},
		"stat:shMin": {
			cat: "Stat",
			desc: "Short Handed Time On Ice",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["shMin"],
			template: "Stat",
			title: "shTOI",
		},
		"stat:ppo": {
			cat: "Stat",
			desc: "Power Play Opportunities",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ppo"],
			template: "Stat",
			title: "PPO",
		},
		"stat:ppPct": {
			cat: "Stat",
			desc: "Power Play Percentage",
			sortSequence: ["desc", "asc"],
			sortType: "number",
			stats: ["ppPct"],
			template: "Stat",
			title: "PP%",
		},
		"stat:gRec": {
			cat: "Stat",
			desc: "Record as primary G",
			sortSequence: ["desc", "asc"],
			sortType: "record",
			stats: ["gRec"],
			template: "Stat",
			title: "Rec",
		},
		"stat:gW": {
			cat: "Stat",
			desc: "Wins as primary G",
			sortSequence: ["desc", "asc"],
			sortType: "record",
			stats: ["gW"],
			template: "Stat",
			title: "GW",
		},
		"stat:gL": {
			cat: "Stat",
			desc: "Losses as primary G",
			sortSequence: ["desc", "asc"],
			sortType: "record",
			stats: ["gL"],
			template: "Stat",
			title: "GL",
		},
		"stat:gT": {
			cat: "Stat",
			desc: "Ties as primary G",
			sortSequence: ["desc", "asc"],
			sortType: "record",
			stats: ["gT"],
			template: "Stat",
			title: "GT",
		},
		"stat:gOTL": {
			cat: "Stat",
			desc: "Overtime losses as primary G",
			sortSequence: ["desc", "asc"],
			sortType: "record",
			stats: ["gOTL"],
			template: "Stat",
			title: "GOTL",
		},
	},
});
const cols: {
	[key: string]: ColTemp;
} = {
	Acquired: {
		cat: "General",
		desc: "How Player Was Acquired",
	},
	Age: {
		attrs: ["age"],
		cat: "General",
		sortType: "number",
		template: "Age",
	},
	"Asking For": {
		attrs: ["contract", "mood"],
		cat: "General",
		sortSequence: ["desc", "asc"],
		sortType: "currency",
		template: "AskingFor",
	},
	College: {
		attrs: ["college"],
		cat: "General",
		template: "College",
	},
	Contract: {
		attrs: ["contract"],
		cat: "General",
		sortSequence: ["desc", "asc"],
		sortType: "currency",
		template: "Contract",
		options: { format: "compact" },
	},
	FullContract: {
		title: "Full Contract",
		attrs: ["contract"],
		cat: "General",
		sortSequence: ["desc", "asc"],
		sortType: "currency",
		template: "Contract",
		options: { format: "full" },
	},
	Country: {
		attrs: ["born"],
		cat: "General",
		template: "Country",
	},
	Projected: {
		attrs: ["contractDesired"],
		cat: "General",
		desc: "Projected Contract Demand",
		sortSequence: ["desc", "asc"],
		sortType: "currency",
		template: "Projected",
	},
	Mood: {
		attrs: ["mood"],
		cat: "General",
		desc: "How Player Feels About Your Team",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		template: "Mood",
		width: "1px",
	},
	CurrentMood: {
		attrs: ["mood"],
		cat: "General",
		desc: "How Player Feels About Their Current Team",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		template: "MoodCurrent",
		title: "Current Mood",
		width: "1px",
	},
	DraftYear: {
		attrs: ["draft"],
		cat: "General",
		sortType: "number",
		template: "DraftYear",
		title: "Draft Year",
	},
	Name: {
		cat: "General",
		ratings: ["skills"],
		attrs: ["pid", "name", "injury", "jerseyNumber", "watch"],
		sortType: "name",
		template: "Name",
	},
	Exp: {
		cat: "General",
		desc: "Contract Expiration",
		attrs: ["contract"],
		sortSequence: ["asc", "desc"],
		sortType: "number",
		template: "Exp",
	},
	Experience: {
		cat: "General",
		desc: "Number of Years in the League",
		attrs: ["experience"],
		sortSequence: ["desc", "asc"],
		sortType: "number",
		template: "Experience",
	},
	Ovr: {
		cat: "General",
		desc: "Overall Rating",
		ratings: ["dovr", "ovr"],
		sortSequence: ["desc", "asc"],
		sortType: "number",
		template: "Ovr",
	},
	"Ovr Drop": {
		cat: "General",
		desc: "Decrease in Overall Rating",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		template: "attr",
		attrs: ["ovrDrop"],
	},
	"Peak Ovr": {
		cat: "General",
		desc: "Peak Overall Rating",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		template: "attr",
		attrs: ["peakOvr"],
	},
	Pos: {
		cat: "General",
		desc: "Position",
		ratings: ["pos"],
		attrs: ["pos"],
		template: "Pos",
	},
	Pot: {
		cat: "General",
		desc: "Potential Rating",
		ratings: ["dpot", "pot"],
		sortSequence: ["desc", "asc"],
		sortType: "number",
		template: "Pot",
	},
	"Pot Drop": {
		cat: "General",
		desc: "Decrease in Potential Rating",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		template: "attr",
		attrs: ["potDrop"],
	},
	Pick: {
		attrs: ["draft"],
		cat: "General",
		desc: "Draft Pick",
		sortType: "draftPick",
		template: "Pick",
	},
	Team: {
		attrs: ["abbrev", "tid"],
		cat: "General",
		sortType: "string",
		stats: ["abbrev", "tid"],
		template: "Team",
	},
	Weight: {
		attrs: ["weight"],
		cat: "General",
		template: "Weight",
	},
	Height: {
		attrs: ["hgt"],
		cat: "General",
		template: "Height",
	},
	InjuryType: {
		cat: "General",
		template: "InjuryType",
		attrs: ["injury"],
		desc: "Type of Injury",
		title: "Type",
	},
	InjuryLength: {
		cat: "General",
		template: "InjuryLength",
		attrs: ["injury"],
		title: "Games",
		desc: "Number of Games",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"rating:endu": {
		cat: "Rating",
		desc: "Endurance",
		ratings: ["endu"],
		sortSequence: ["desc", "asc"],
		sortType: "number",
		template: "Rating",
		title: "End",
	},
	"rating:hgt": {
		cat: "Rating",
		desc: "Height",
		ratings: ["hgt"],
		sortSequence: ["desc", "asc"],
		sortType: "number",
		template: "Rating",
		title: "Hgt",
	},
	"rating:spd": {
		cat: "Rating",
		desc: "Speed",
		ratings: ["spd"],
		sortSequence: ["desc", "asc"],
		sortType: "number",
		template: "Rating",
		title: "Spd",
	},
	"rating:stre": {
		cat: "Rating",
		desc: "Strength",
		ratings: ["stre"],
		sortSequence: ["desc", "asc"],
		sortType: "number",
		template: "Rating",
		title: "Str",
	},
	"stat:gp": {
		cat: "Stat",
		desc: "Games Played",
		options: { decimals: 0 },
		sortSequence: ["desc", "asc"],
		sortType: "number",
		stats: ["gp"],
		template: "Stat",
		title: gp,
	},
	"stat:gs": {
		cat: "Stat",
		desc: "Games Started",
		options: { decimals: 0 },
		sortSequence: ["desc", "asc"],
		sortType: "number",
		stats: ["gs"],
		template: "Stat",
		title: "GS",
	},
	"stat:jerseyNumber": {
		cat: "General",
		desc: "Jersey Number",
		options: { decimals: 0 },
		sortSequence: ["asc", "desc"],
		sortType: "number",
		stats: ["jerseyNumber"],
		template: "Stat",
		title: "#",
	},
	"stat:min": {
		cat: "Stat",
		desc: isSport("hockey") ? "Time On Ice" : "Minutes",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		stats: ["min"],
		template: "Stat",
		title: isSport("hockey") ? "TOI" : "MP",
	},
	"stat:yearsWithTeam": {
		cat: "General",
		desc: "Years With Team",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		stats: ["yearsWithTeam"],
		template: "Stat",
		title: "YWT",
	},
	...sportSpecificCols,
};

const legacyCols: {
	[key: string]: Partial<Col>;
} = {
	"": {
		sortSequence: ["desc", "asc"],
	},
	"#": {},
	"@": {
		desc: "Home or Away",
	},
	"#AS": {
		desc: "Number of All-Star Selections",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"%": {
		desc: "Percentage",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Active: {
		desc: "Number of Players Still Active",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"# Fathers": {
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	HoF: {
		desc: "Number of Players in the Hall of Fame",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"# Brothers": {
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"# Players": {
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"# Seasons": {
		desc: "Number of Seasons",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"# Sons": {
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"# Teams": {
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"# Trades": {
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	A: {
		desc: "Attempted",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Actions: {},
	"Avg Attendance": {
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	AvgAge: {
		desc: "Average age, weighted by minutes played",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "Age",
	},
	Born: {
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"Cap Space": {
		sortSequence: ["desc", "asc"],
		sortType: "currency",
	},
	"Captain 1": {
		sortType: "name",
	},
	"Captain 2": {
		sortType: "name",
	},
	Cash: {
		sortSequence: ["desc", "asc"],
		sortType: "currency",
	},
	Change: {
		desc: "Difference between pre-lottery rank and draft lottery result",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Conference: {},
	Count: {
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Created: {
		desc: "Created Date",
		searchType: "string",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Current: {
		desc: "Current Team Rating (With Injuries)",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Details: {},
	Died: {
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Diff: {
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Difficulty: {
		sortSequence: ["desc", "asc"],
	},
	Division: {},
	Draft: {
		noSearch: true,
		sortSequence: [],
	},
	"Draft Picks": {
		sortSequence: [],
		sortType: "draftPick",
	},
	"Dunk Winner": {
		desc: "Slam Dunk Contest Winner",
		sortType: "name",
	},
	Finals: {
		desc: "Finals Appearances",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"Finals Won": {
		desc: "Finals Won",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"Finals Lost": {
		desc: "Finals Lost",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	From: {},
	GB: {
		desc: "Games Back",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Games: {
		desc: "Number of Games",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	GOAT: {
		desc: "GOAT Score",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Healthy: {
		desc: "Team Rating (When Healthy)",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	HOF: {
		sortSequence: ["desc", "asc"],
	},
	Injury: {},
	L: {
		desc: "Losses",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	L10: {
		desc: "Last Ten Games",
		sortSequence: ["desc", "asc"],
		sortType: "lastTen",
	},
	Last: {
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"Last Played": {
		desc: "Last Played Date",
		sortSequence: ["desc", "asc"],
		searchType: "string",
		sortType: "number",
	},
	"Last Season": {
		desc: "Last Season with Team",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"League Champion": {},
	League: {
		desc: "League Name",
	},
	Links: {
		noSearch: true,
		sortSequence: [],
	},
	M: {
		desc: "Made",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	MVP: {
		desc: "Most Valuable Player",
		sortType: "name",
	},
	Name: {
		sortType: "name",
	},
	Normal: {
		desc: "Normal Difficulty",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Hard: {
		desc: "Hard Difficulty",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Insane: {
		desc: "Insane Difficulty",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Negotiate: {
		sortSequence: [],
	},
	Note: {},
	Odds: {
		desc: "Pre-lottery odds of getting this pick",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Opp: {
		desc: "Opponent",
	},
	PA: {
		desc: `${isSport("hockey") ? "Goals" : "Points"} Against`,
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: isSport("hockey") ? "GA" : undefined,
	},
	PS: {
		desc: `${isSport("hockey") ? "Goals" : "Points"} Scored`,
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: isSport("hockey") ? "GF" : undefined,
	},
	"PA/g": {
		desc: `${isSport("hockey") ? "Goals" : "Points"} Against Per Game`,
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: isSport("hockey") ? "GA" : undefined,
	},
	"PS/g": {
		desc: `${isSport("hockey") ? "Goals" : "Points"} Scored Per Game`,
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: isSport("hockey") ? "GF" : undefined,
	},
	Payroll: {
		sortSequence: ["desc", "asc"],
		sortType: "currency",
	},
	Phase: {
		desc: "League Season and Phase",
		sortSequence: ["desc", "asc"],
	},
	Pick: {
		desc: "Draft Pick",
		sortType: "draftPick",
	},
	Pop: {
		desc: "Region Population",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Playoffs: {
		desc: "Playoff Appearances",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"Pre-Lottery": {
		desc: "Pre-lottery rank",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Prog: {
		desc: "Progression From Previous Season",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"Profit (YTD)": {
		sortSequence: ["desc", "asc"],
		sortType: "currency",
	},
	Received: {
		desc: "Assets Received in Trade",
	},
	Record: {
		desc: "Record",
		sortType: "record",
	},
	Relation: {},
	Result: {},
	Retired: {
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"Revenue (YTD)": {
		sortSequence: ["desc", "asc"],
		sortType: "currency",
	},
	"Roster Spots": {
		desc: "Number of Open Roster Spots",
		sortSequence: ["desc", "asc"],
	},
	"Rounds Lost": {
		desc: "Playoff Rounds Lost",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"Rounds Won": {
		desc: "Playoff Rounds Won",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"Runner Up": {},
	Season: {
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Seed: {
		desc: "Playoff Seed",
		sortType: "number",
	},
	Start: {
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Strategy: {},
	T: {
		desc: "Ties",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	"Ticket Price": {
		sortSequence: ["desc", "asc"],
		sortType: "currency",
	},
	Trade: {
		desc: "Ties",
		noSearch: true,
	},
	OTL: {
		desc: "Overtime Losses",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Team: {},
	"Three-Point Winner": {
		desc: "Three-Point Contest Winner",
		sortType: "name",
	},
	Titles: {
		desc: "Championships Won",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Type: {
		desc: "Type of Game",
	},
	W: {
		desc: "Wins",
		sortSequence: ["desc", "asc"],
		sortType: "number",
	},
	Year: {
		sortType: "number",
	},
	Summary: {},
	"stat:mov": {
		desc: "Average Margin of Victory",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "MOV",
	},
	"stat:diff": {
		desc: "Point Differential",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "Diff",
	},
	"count:allDefense": {
		desc: "All-Defensive Team",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "ADT",
	},
	"count:allLeague": {
		desc: "All-League Team",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "ALT",
	},
	"count:allRookie": {
		desc: "All-Rookie Team",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "ART",
	},
	"count:allStar": {
		desc: "All-Star",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "AS",
	},
	"count:allStarMVP": {
		desc: "All-Star MVP",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "ASMVP",
	},
	"count:bestRecord": {
		desc: "Best Record",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "BR",
	},
	"count:bestRecordConf": {
		desc: "Best Conference Record",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "BRC",
	},
	"count:dpoy": {
		desc: "Defensive Player of the Year",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "DPOY",
	},
	"count:dfoy": {
		desc: "Defensive Forward of the Year",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "DFOY",
	},
	"count:goy": {
		desc: "Goalie of the Year",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "GOY",
	},
	"count:mip": {
		desc: "Most Improved Player",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "MIP",
	},
	"count:mvp": {
		desc: "Most Valuable Player",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "MVP",
	},
	"count:roy": {
		desc: "Rookie of the Year",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "ROY",
	},
	"count:smoy": {
		desc: "Sixth Man of the Year",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "SMOY",
	},
	"count:oroy": {
		desc: "Offensive Rookie of the Year",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "OROY",
	},
	"count:droy": {
		desc: "Defensive Rookie of the Year",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "DROY",
	},
	"award:dpoy": {
		desc: "Defensive Player of the Year",
		sortType: "name",
		title: "DPOY",
	},
	"award:dfoy": {
		desc: "Defensive Forward of the Year",
		sortType: "name",
		title: "DFOY",
	},
	"award:goy": {
		desc: "Goalie of the Year",
		sortType: "name",
		title: "GOY",
	},
	"award:finalsMvp": {
		desc: `${isSport("hockey") ? "Playoffs" : "Finals"} Most Valuable Player`,
		sortType: "name",
		title: `${isSport("hockey") ? "Playoffs" : "Finals"} MVP`,
	},
	"award:mip": {
		desc: "Most Improved Player",
		sortType: "name",
		title: "MIP",
	},
	"award:mvp": {
		desc: "Most Valuable Player",
		sortType: "name",
		title: "MVP",
	},
	"award:roy": {
		desc: "Rookie of the Year",
		sortType: "name",
		title: "ROY",
	},
	"award:smoy": {
		desc: "Sixth Man of the Year",
		sortType: "name",
		title: "SMOY",
	},
	"award:oroy": {
		desc: "Offensive Rookie of the Year",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "OROY",
	},
	"award:droy": {
		desc: "Defensive Rookie of the Year",
		sortSequence: ["desc", "asc"],
		sortType: "number",
		title: "DROY",
	},
};

export function getAllCols(): Col[] {
	return Object.entries(cols).map(([name, col]): Col => {
		return {
			...col,
			title: col.title ?? name,
			key: name,
		};
	});
}

export default (
	keys: string[],
	overrides: Record<string, Partial<MetaCol>> = {},
): MetaCol[] => {
	return keys.flatMap(key => {
		const col: MetaCol = {
			title: key,
			...(cols[key] ?? legacyCols[key] ?? {}),
			...overrides[key],
			key: key,
		};

		return [col];
	});
};
