PHASE_PRESEASON = 0
PHASE_REGULAR_SEASON = 1
PHASE_AFTER_TRADE_DEADLINE = 2
PHASE_PLAYOFFS = 3
PHASE_BEFORE_DRAFT = 4
PHASE_DRAFT = 5
PHASE_AFTER_DRAFT = 6
PHASE_RESIGN_PLAYERS = 7
PHASE_FREE_AGENCY = 8

