// @flow

const stats = {
    derived: ["qbW", "qbL", "cmpPct", "qbrat"],
    raw: [
        "gp",
        "gs",
        "min",
        "fmb",
        "fmbLost",
        "pssCmp",
        "pss",
        "pssYds",
        "pssTD",
        "pssInt",
        "pssLng",
        "pssSk",
        "pssSkYds",
        "rus",
        "rusYds",
        "rusTD",
        "rusLng",
        "tgt",
        "rec",
        "recYds",
        "recTD",
        "recLng",
        "pr",
        "prYds",
        "prTD",
        "prLng",
        "kr",
        "krYds",
        "krTD",
        "krLng",
        "defInt",
        "defIntYds",
        "defIntTD",
        "defIntLng",
        "defPssDef",
        "defFmbFrc",
        "defFmbRec",
        "defFmbYds",
        "defFmbTD",
        "defSk",
        "defTckSolo",
        "defTckAst",
        "defTckLoss",
        "defSft",
        "fg0",
        "fga0",
        "fg20",
        "fga20",
        "fg30",
        "fga30",
        "fg40",
        "fga40",
        "fg50",
        "fga50",
        "fgLng",
        "xp",
        "xpa",
        "pnt",
        "pntYds",
        "pntLng",
        "pntBlk",
        "pen",
        "penYds",
    ],
};

export default stats;
