// @flow

const stats = {
    derived: [
        "oppFg",
        "oppFga",
        "oppFgAtRim",
        "oppFgaAtRim",
        "oppFgLowPost",
        "oppFgaLowPost",
        "oppFgMidRange",
        "oppFgaMidRange",
        "oppTp",
        "oppTpa",
        "oppFt",
        "oppFta",
        "oppOrb",
        "oppDrb",
        "oppAst",
        "oppTov",
        "oppStl",
        "oppBlk",
        "oppPf",
        "oppPts",
    ],
    raw: [
        "gp",
        "min",
        "fg",
        "fga",
        "fgAtRim",
        "fgaAtRim",
        "fgLowPost",
        "fgaLowPost",
        "fgMidRange",
        "fgaMidRange",
        "tp",
        "tpa",
        "ft",
        "fta",
        "orb",
        "drb",
        "ast",
        "tov",
        "stl",
        "blk",
        "pf",
        "pts",
    ],
};

export default stats;
