const { csvParse } = require("d3-dsv");
const fs = require("fs");
const path = require("path");

const csv = fs.readFileSync(path.join(__dirname, "races.csv"), "utf8");
const rows = csvParse(csv);
const templates = {};

// First pass - get the "template" countries
for (const row of rows) {
	if (row.copy_from === "") {
		templates[row.country] = {
			asian: parseInt(row.asian),
			black: parseInt(row.black),
			brown: parseInt(row.brown),
			white: parseInt(row.white),
		};
	}
}

let code = `// This file is generated by tools/races.js

import type { Race } from "../../common/types";

const defaultRaces: Record<string, Record<Race, number>> = ${JSON.stringify(
	templates,
	null,
	"\t",
)};

`;

// Second pass - get the other countries based on templates
for (const row of rows) {
	if (row.copy_from !== "") {
		code += `defaultRaces["${row.country}"] = defaultRaces["${row.copy_from}"];\n`;
	}
}

code += `\nexport default defaultRaces;\n`;

console.log(code);
const filename = path.join(__dirname, "../src/worker/data/defaultRaces.ts");
fs.writeFileSync(filename, code);
console.log(`Wrote data to ${filename}`);
