import { csvParse } from "d3-dsv";
import fs from "fs";
import path from "path";

const __dirname = path.dirname(new URL(import.meta.url).pathname);

const csv = fs.readFileSync(path.join(__dirname, "races.csv"), "utf8");
const rows = csvParse(csv);
const templates = {};

// First pass - get the "template" countries
for (const row of rows) {
	if (row.copy_from === "") {
		templates[row.country] = {
			asian: parseInt(row.asian),
			black: parseInt(row.black),
			brown: parseInt(row.brown),
			white: parseInt(row.white),
		};
	}
}

let code = `// This file is generated by tools/races.js

import { isSport } from "../../common";
import type { Race } from "../../common/types";

const defaultRaces: Record<string, Record<Race, number>> = ${JSON.stringify(
	templates,
	null,
	"\t",
)};

if (isSport("hockey")) {
	defaultRaces.USA = {
		asian: 2,
		black: 2,
		brown: 3,
		white: 93,
	};
	defaultRaces.Germany = defaultRaces.USA;
	defaultRaces.Spain = defaultRaces.USA;
}

`;

// Second pass - get the other countries based on templates
for (const row of rows) {
	if (row.copy_from !== "") {
		code += `defaultRaces["${row.country}"] = defaultRaces["${row.copy_from}"];\n`;
	}
}

code += `\nexport default defaultRaces;\n`;

const filename = path.join(__dirname, "../src/worker/data/defaultRaces.ts");
fs.writeFileSync(filename, code);
console.log(`Wrote data to ${filename}`);
