export const gameAttributesSyncedToUi = [
	"alwaysShowCountry",
	"challengeNoRatings",
	"challengeNoTrades",
	"currencyFormat",
	"fantasyPoints",
	"gameOver",
	"gender",
	"godMode",
	"hideDisabledTeams",
	"homeCourtAdvantage",
	"lid",
	"neutralSite",
	"numPeriods",
	"numWatchColors",
	"phase",
	"quarterLength",
	"season",
	"spectator",
	"startingSeason",
	"teamInfoCache",
	"userTid",
	"userTids",
] as const;
