import { PHASE, PLAYER } from "../../../common";
import { g, helpers, random } from "../../util";
import type {
	MinimalPlayerRatings,
	Phase,
	Player,
	PlayerWithoutKey,
} from "../../../common/types";

/**
 * Adds player to the free agents list.
 *
 * This should be THE ONLY way that players are added to the free agents
 * list, because this will also calculate their demanded contract and mood.
 *
 * @memberOf core.player
 * @param {Object} p Player object.
 * @param {?number} phase An integer representing the game phase to consider this transaction under (defaults to g.get("phase") if null).
 * @param {Array.<number>} baseMoods Vector of base moods for each team from 0 to 1, as generated by genBaseMoods.
 */
const addToFreeAgents = (
	p: Player<MinimalPlayerRatings> | PlayerWithoutKey<MinimalPlayerRatings>,
	phase: Phase,
	baseMoods: number[],
) => {
	p.numDaysFreeAgent = 0;
	p.tid = PLAYER.FREE_AGENT;
	p.ptModifier = 1; // Reset
};

export default addToFreeAgents;
